name: imbalanced_classification
channels:
  - defaults
dependencies:
  - python=3.10.12
  - scipy==1.13.0
  - imbalanced_learn==0.11.0
  - imblearn==0.0
  - matplotlib==3.8.0
  - numpy==1.26.4
  - pandas==1.5.3
  - scikit_learn==1.3.1
  - seaborn==0.13.2